apiVersion: v1
kind: Service 
metadata:
  name: myapp
spec:
  type: NodePort
  ports: 
   - targetPort: 80 # Port of the pod
     port: 80 # Port of the service
     nodePort: 30008 # Port of the node
  selector: 
    app: myapp
    type: frontend